SANDBOX_URL = "https://api-public.sandbox.pro.coinbase.com"
LIVE_URL = "https://api.pro.coinbase.com"
SANDBOX = "sandbox"
LIVE = "live"
API_KEY = "api_key"
API_BASE64 = "api_base64"
API_PASS = "api_pass"